micronaut:
  application:
    name: demo
  security:
    authentication: cookie
    oauth2:
      clients:
        default:
          client-id: ${OAUTH_CLIENT_ID}
          client-secret: ${OAUTH_CLIENT_SECRET}
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
hazelcast.network.addresses: '[''121.0.0.1:5701'']'
netty:
  default:
    allocator:
      max-order: 3
